### ISSUE TITLE
Implement longer responses in the app

### ISSUE THREAD

**Issue by siliconwitch** [brilliantlabsAR/argpt-for-ios#16]
I've enabled the ability to print longer responses than a single MTU allows. To do so, simply send multiple `res:` commands back to back:

```python
'res:The quick...fox'
'res:jumped over...lazy'
'res:dog.'
```

**Comment by siliconwitch** [comment]
Actually no, sorry. `_bluetooth.sendData(text: "res:" + message)` doesn't split the message quite right. It splits up, but `res:` isn't appended to each new MTU. I.e, this turns into:
```
'res:The quick...fox'
'jumped over...lazy'
'dog.'
```

**Comment by trzy** [comment]
Done. res: and err: payloads are split up to be maxWriteLength-4 bytes, and then either err: or res: is prepended to each. However, no end signal is sent. Let me know if you need it.
