### ISSUE TITLE
Why does the text get offset

### ISSUE THREAD

**Issue by siliconwitch** [brilliantlabsAR/argpt-for-ios#17]
Happens randomly. Perhaps because we're driving the text module at 50fps. Could that cause an issue?

**Comment by josuah** [comment]
For now I am adding raw REPL support to the `serial_console.py`.

Then I can test a new implementation of display.py with extra logging.

If that is not enough, I'll try to get it actually running on an FPGA, and get *some* output out of it in one way or another.

**Comment by siliconwitch** [comment]
Still happening, but removing from here as it's purely a firmware bug
