### ISSUE TITLE
Crashing again

### ISSUE THREAD

**Issue by siliconwitch** [brilliantlabsAR/argpt-for-ios#18]
Much less frequent, but still happens.

**Comment by josuah** [comment]
Several crashes were reported while using `async` in combination with buttons.
I will try a minimal reproducer that way.

**Comment by siliconwitch** [comment]
We're not using async in this app. I wonder if it could be linked to whatever causes the text offset. We can Get #17 figured out first, and then see if this happens. It's fairly rare
