### ISSUE TITLE
Match the firmware update progress wording to the Figma design

### ISSUE THREAD

**Issue by siliconwitch** [brilliantlabsAR/argpt-for-ios#46]
Specifically, we need to tell the user to keep the app open here.

![Image](https://github.com/brilliantlabsAR/argpt-for-ios/assets/7815190/66974294-2404-4cd8-8fbc-c340a5b215a8)

![Image](https://github.com/brilliantlabsAR/argpt-for-ios/assets/7815190/2db9077c-aad8-4483-8561-c18f326e590a)

**Comment by trzy** [comment]
Do you want to use this for both software and FPGA?

**Comment by trzy** [comment]
Also, the background view text in Figma references pairing but note that updates can happen any time mismatch is detected (not necessarily during pairing). Shouldn't we have different text in the background?

**Comment by siliconwitch** [comment]
> Do you want to use this for both software and FPGA?

Yes. From the users perspective, it’s one update. You can make the bar represent 50% of each update 

> Also, the background view text in Figma references pairing but note that updates can happen any time mismatch is detected (not necessarily during pairing). Shouldn't we have different text in the background?

Yea possibly. I’ll take a look at the Figma and let you know. Feel free if you have any suggestion

**Comment by trzy** [comment]
What do you mean by the bar? There isn't a progress bar currently. Do you mean I should be going from 0-50% for the firmware update and 50-100% for the FPGA update?

**Comment by siliconwitch** [comment]
Yeah sorry, I meant the percentage. Precisely as you’ve described

**Comment by trzy** [comment]
Done.
