### ISSUE TITLE
Add some hysteresis to the Connect button

### ISSUE THREAD

**Issue by siliconwitch** [brilliantlabsAR/argpt-for-ios#53]
The Connect button flickers due to the RSSI jumping around. Some hysteresis here should help. 

Show connect once RSSI goes above -65dBm, and then grey it again once it goes below -85dBm

![Image](https://user-images.githubusercontent.com/7815190/257772467-be3cb1f6-82d3-4168-a3ee-369fcd97a58c.gif)

**Comment by trzy** [comment]
Done.
