### ISSUE TITLE
[feature request] Add a mode to use a default query instead of speaking

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/argpt-for-ios#77]
For instance, "give me more detail about what is that image".

Then gestures like one tap on Frame would run that default query, saving from speaking out loud, which might be inappropriate in a quiet place. This is also faster to transfer no audio at all, and immediately start transferring the image.

Some extra gestures could further allow selecting among several default queries.

https://discord.com/channels/963222352534048818/984966420603482182/1208934320077799484
https://discord.com/channels/963222352534048818/984966420603482182/1225391329161383936

**Comment by Elias966** [comment]
I want this Feature also , because this what is stopping me from preordering it

**Comment by josuah** [comment]
https://discord.com/channels/963222352534048818/984966420603482182/1235716447993466992

**Comment by josuah** [comment]
Turned into this on noa-flutter:
- https://github.com/brilliantlabsAR/noa-flutter/issues/166

**Comment by siliconwitch** [comment]
Released
